name: Swift

on:
  push:
    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]
    
#env:
#  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  build:

    runs-on: macos-11

    steps:
#    - uses: actions/checkout@v2
#    - name: Build Generator
#      run: swift build --target Generator
#    - name: Run Generator
#      run: swift run Generator
    - name: Check for new updates
      run: |
        echo "Checking for updates"
        echo "No updates, bye bye"
        exit 0
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v --enable-test-discovery --enable-code-coverage
#    # https://nacho4d-nacho4d.blogspot.com/2020/10/code-coverage-for-swift-package-projects.html
#    - name: Convert code coverage
#      run: xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name SlabPackageTests) > info.lcov
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v2
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: info.lcov
#        fail_ci_if_error: true
