name: Swift

on:
  push:
    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]
    
#env:
#  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  Generation:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build Generator
      run: swift build --target Generator
    - name: Run Generator
      run: swift run Generator
    - name: Check for changes
      run: |
        # true if changes detected
        isChanged=$(git diff-index --quiet HEAD -- || echo "true");
        echo "IS_CHANGED=$isChanged" >> $GITHUB_ENV
        if [[ $isChanged == "true" ]]; then
            echo "Changes detected"
        else
            echo "No changes detected"
        fi
    - name: "Ensure package still builds"
      if: ${{ env.IS_CHANGED == 'true' }}
      run: swift build --target Devices
    - name: "Create pull request"
      if: ${{ env.IS_CHANGED == 'true' }}
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Generator run"
        branch: "automated/generator"
        delete-branch: true
        title: "Automated: Generator changes"
        body: ""
        assignees: "ptrkstr"
    
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v --enable-test-discovery --enable-code-coverage
#    # https://nacho4d-nacho4d.blogspot.com/2020/10/code-coverage-for-swift-package-projects.html
#    - name: Convert code coverage
#      run: xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name SlabPackageTests) > info.lcov
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v2
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: info.lcov
#        fail_ci_if_error: true
